<table style="width='100%'">                                                                                                                                                                                                                             
<?php                                                                                                                                                                                                                                                    
$con = mysqli_connect("127.0.0.1","root","avianrox123","server_nfo");                                                                                                                                                                                    
                                                                                                                                                                                                                                                         
if (mysqli_connect_errno()) {                                                                                                                                                                                                                            
  echo "Failed to connect to MySQL: " . mysqli_connect_error();                                                                                                                                                                                          
  exit();                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                         
// Perform query                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                         
if ($result = mysqli_query($con, 'SELECT server_name FROM server_nfo WHERE server_id=420')) {                                                                                                                                                            
  while ($row = mysqli_fetch_row($result)){                                                                                                                                                                                                              
        //if(explode(",", $row[0]) != false){                                                                                                                                                                                                            
        //      $result = explode(",", $row[0]);                                                                                                                                                                                                         
        //      $amount_of_users = count($result);                                                                                                                                                                                                       
        //      while($i = 0, $i < $amount_of_users, $i++){                                                                                                                                                                                              
        //              echo "<tr>" . $result[i] . "</tr>";                                                                                                                                                                                              
        //      }                                                                                                                                                                                                                                        
        //} else {                                                                                                                                                                                                                                       
                echo "<tr><th>" . $row[0] . "</th></tr>";                                                                                                                                                                                                
        //}                                                                                                                                                                                                                                              
  }                                                                                                                                                                                                                                                      
  // Free result set                                                                                                                                                                                                                                     
  mysqli_free_result($result);                                                                                                                                                                                                                           
}                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                         
mysqli_close($con);                                                                                                                                                                                                                                      
?>                                                                                                                                                                                                                                                       
</table>                                
