<?php                                                                                                                                                                                                                                                    
        session_start();                                                                                                                                                                                                                                 
        if(!isset($_SESSION['UniversalID'])){header('Location: /?error=you_have_not_logged_in');}                                                                                                                                                        
?>                                                                                                                                                                                                                                                       
<form id="server_crt" method="POST" action="server_generator.php" enctype="multipart/form-data">                                                                                                                                                         
        <label for="servername">server name:</label>                                                                                                                                                                                                     
        <input name="servername" id="servername" type="text" required>                                                                                                                                                                                   
        <label for="servertopic">server topic:</label>                                                                                                                                                                                                   
        <input name="servertopic" id="servertopic" type="text">                                                                                                                                                                                          
        <button type="submit" value="submit">Send</button>                                                                                                                                                                                               
</form>         
