<?php                                                                                                                                                                                                                        
if(isset($_SESSION['Username'])){                                                                                                                                                                                            
                                                                                                                                                                                                                             
        echo '<link type="text/css" rel="stylesheet" href="PAMregister/users/".$SESSION["Username"]."CSS/css1.css">';                                                                                                        
  }else{                                                                                                                                                                                                                     
    echo '<link type="text/css" rel="stylesheet" href="css/Stylesheet1.css">';                                                                                                                                               
  }                                                                                                                                                                                                                          
?>                                                                                                                                                                                                                           
                                                                                                                                                                                                                             
<link rel="icon" type="image/png" href="/src/images/avianalterantive.png"/>                                                                                                                                                  
<div>                                                                                                                                                                                                                        
                                                                                                                                                                                                                             
        <hr id="PinkBar">                                                                                                                                                                                                    
        <hr id="PinkBar">                                                                                                                                                                                                    
        <hr id="PinkBar">                                                                                                                                                                                                    
        <hr id="PinkBar">                                                                                                                                                                                                    
                <div id="container">                                                                                                                                                                                         
                        <div id="Title">                                                                                                                                                                                     
                                Welcome To Avian                                                                                                                                                                             
                        </div>                                                                                                                                                                                               
                        <a id="anon" href="/anonchat.php"> Log in as anon</a>                                                                                                                                                
                        <a id="login" href="/PAMver10.php"> Log in</a>                                                                                                                                                       
                        <a id="dms"  href="/accountScreen.php">DMs</a>                                                                                                                                                       
                </div>                                                                                                                                                                                                       
        <hr id="PinkBar">                                                                                                                                                                                                    
        <hr id="PinkBar">                                                                                                                                                                                                    
        <hr id="PinkBar">                                                                                                                                                                                                    
        <hr id="PinkBar">                                                                                                                                                                                                    
</div>        
